data:
  type: dataset.nerf.Synthetic
  params:
    root: ./data/nerf_synthetic
    scene: ship
    white_bkgd: True
    init_points: True

method:
  text: the ship

  curve_params:
    proj_mode: persp
    proj_scale: 1.0
    blender: True

    gap: 0.01
    center: [0.0, 0.0, 0.0]
    rand_mode: bbox
    upside: False
    boundaries: [1.0, 1.0, 1.0]

    num_strokes: 64