name: 3Doodle
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.3.1
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - libstdcxx-ng
  - pip:
    - torch-tools==0.0.35
    - opencv-python==4.8.1.78
    - numpy==1.24.4
    - imageio==2.31.1
    - cmake==3.27.0
    - typing==3.7.4.3
    - tqdm==4.65.0
    - PyYAML==6.0
    - scikit-image==0.21.0
    - cssutils==2.7.1
    - rich==13.7.0
    - chardet==5.2.0